## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN','NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
df = application_df['APPLICATION_TYPE'].value_counts().reset_index()

# Rename the columns
df = df.rename(columns={'index': 'APPLICATION_TYPE', 'APPLICATION_TYPE': 'COUNT'})
df

   APPLICATION_TYPE  COUNT
0                T3  27037
1                T4   1542
2                T6   1216
3                T5   1173
4               T19   1065
5                T8    737
6                T7    725
7               T10    528
8                T9    156
9               T13     66
10              T12     27
11               T2     16
12              T25      3
13              T14      3
14              T29      2
15              T15      2
16              T17      1

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = []
for x in range(len(df)):
  if df.iloc[x,1]<200:
    application_types_to_replace.append(df.iloc[x, 0])
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
df1 = application_df['CLASSIFICATION'].value_counts().reset_index()

# Rename the columns
df1 = df1.rename(columns={'index': 'CLASSIFICATION', 'CLASSIFICATION': 'COUNT'})
df1

   CLASSIFICATION  COUNT
0           C1000  17326
1           C2000   6074
2           C1200   4837
3           C3000   1918
4           C2100   1883
..            ...    ...
66          C4120      1
67          C8210      1
68          C2561      1
69          C4500      1
70          C2150      1

[71 rows x 2 columns]

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
value = application_df['CLASSIFICATION'].value_counts()
filter = value[value>1]
filter

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = []
for x in range(len(df1)):
  if df1.iloc[x,1]<1000:
    classifications_to_replace.append(df1.iloc[x, 0])

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`

encoded_df = pd.get_dummies(application_df, columns=[	'APPLICATION_TYPE',	'AFFILIATION',	'CLASSIFICATION',	'USE_CASE',	'ORGANIZATION',	'INCOME_AMT',	'SPECIAL_CONSIDERATIONS'])
encoded_df['STATUS'] = application_df['STATUS']
encoded_df['ASK_AMT'] = application_df['ASK_AMT']
encoded_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL']
X = encoded_df
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train,  y_test = train_test_split(X,y)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=1,activation ="relu", input_dim=44))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=1,activation ="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1,activation ="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 1)                 45

 dense_1 (Dense)             (None, 1)                 2

 dense_2 (Dense)             (None, 1)                 2

=================================================================
Total params: 49 (196.00 Byte)
Trainable params: 49 (196.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=['accuracy'])

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.4983 - accuracy: 0.8555
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.2135 - accuracy: 0.9747
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.1475 - accuracy: 0.9759
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.1221 - accuracy: 0.9759
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.1101 - accuracy: 0.9759
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.1041 - accuracy: 0.9759
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.1009 - accuracy: 0.9759
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0996 - accuracy: 0.9760
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0990 - accuracy: 0.9760
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0989 - accuracy: 0.9760
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0987 - accuracy: 0.9760
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.0988 - accuracy: 0.9760

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.1114 - accuracy: 0.9721 - 461ms/epoch - 2ms/step
Loss: 0.11138001084327698, Accuracy: 0.9721282720565796

In [19]:
# Export our model to HDF5 file
from keras.models import load_model

# Define the filename for your HDF5 file
AlphabetSoupCharity = 'AlphabetSoupCharity.h5'

# Save the model to an HDF5 file
nn.save(AlphabetSoupCharity)

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(